[package]
name = "web3"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { version = "0.11", features = ["full"] }
eyre = "0.6.12"
tokio = { version = "1.44.1", features = ["full"] }
alloy-signer-local = { version = "0.11.1", features = ["keystore"] }
rand = "0.8.5"
tempfile = "3.8.0"